### ISSUE TITLE
test simulator support after fixing #84

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#106]
https://github.com/zebrunner/mcloud-ios/issues/84

we have to test automatic detection of the device type and version for simulators. potentially it should be adjusted

**Comment by vdelendik** [comment]
1. improved authorize-simulators using `xcrun simctl list --json > ${SIMULATORS}`
2. reused jq to define available simulators and their type (deviceTypeIdentifier)
3. automatically detected Phone/Tablet/tvOS DEVICETYPE

changes: https://github.com/zebrunner/mcloud-ios/pull/121

testing should include running iOS tests over phone/tablet and apple tv. make sure to double check that appium default params are valid: platformName, platformVersion etc

**Comment by dhreben** [comment]
Mobile Sample (iOS) jobs  run on phone/tablet and Apple TV worked seccesfully  alsol  video is present.
<img width="275" alt="Screenshot 2022-04-06 at 16 26 55" src="https://user-images.githubusercontent.com/50950954/161985425-709fe949-35e3-4205-b9ff-3beda2dcf970.png">
