### ISSUE TITLE
add requirements to setup auto-login for user who want to use launch agent scripts

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#11]
automatic startup of WDA requires GUI session. Also steps to setup automatic services startup are configure to use user's launch agents configuration.
Need to add for launchd readme steps requirement about automatic user reboot. That's the only approach to strat everything after mac reboot

**Comment by vdelendik** [comment]
done

**Comment by dhreben** [comment]
Verified.
<img width="873" alt="Screenshot 2021-01-04 at 20 29 10" src="https://user-images.githubusercontent.com/50950954/103562096-929ca880-4ecb-11eb-81ce-84d2608c7e43.png">
