### ISSUE TITLE
detect appleTV as device class correctly

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#111]
we use `tvos` as device type for grid etc. zebrunner.sh should be adjusted to detect ApptleTV device class correctly and register valid DEVICETYPE

**Comment by vdelendik** [comment]
still have conflicts in deviceType and platformName values.
valid values are:
DEVICETYPE='tvOS'
PLATFORM_NAME=iOS

**Comment by vdelendik** [comment]
done for real devices and simulators: https://github.com/zebrunner/mcloud-ios/pull/121

**Comment by dhreben** [comment]
Verified
