### ISSUE TITLE
Add support udid by ./zebrunner.sh down

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#117]
Make sense to do support udid in the ./zebrunner.sh down script

It's also important to add a confirmation that we remove logs and Appium/WDA temp data.

**Comment by vdelendik** [comment]
fixed. make sure to verify that 
1. services stopped (appium, wda and stf)
2. temp data removed from `./tmp/AppiumData/$udid` and `./tmp/DerivedData/$udid`

also submitted #122 improvements
