### ISSUE TITLE
restart by uuid is broken

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#119]
`./zebrunner.sh resrtart uuid` - it restart services for all devices

**Comment by vdelendik** [comment]
fixed, it should be possible to restart single device/simulator services using `./zebrunner.sh restart <uuid>`
Also improved log messages for regular `./zebrunner.sh restart` adding at the end such message so users could understand better next steps using `tail`, make sure to confirm message is valid and might be used to track agents.log
```
Starting MCloud services...
Use 'tail -f ./logs/agents.log' to control startup process.
```

**Comment by dhreben** [comment]
Verified.
