### ISSUE TITLE
add requirement to install cmake on iOS mac slave

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#12]
cmake is needed to compine new jpeg-turbo dependency.
steps to follow can be find here: https://cmake.org/install/

**Comment by vdelendik** [comment]
need retest using 8.17.0 node as original error was deceted when `npm install` was executed using v14

**Comment by vdelendik** [comment]
fixed in readme

**Comment by dhreben** [comment]
Verified:
<img width="665" alt="Screenshot 2021-02-01 at 19 03 30" src="https://user-images.githubusercontent.com/50950954/106484094-50618980-64c0-11eb-9c64-86203e113892.png">
