### ISSUE TITLE
iOS agent source code

### ISSUE THREAD

**Issue by Sabomato** [zebrunner/mcloud-ios#120]
Maybe this is an obvious question, but is iOS agent's source code publicly available?

**Comment by vdelendik** [comment]
@Sabomato from MCloud perspective this repository is publicly available source code for iOS agent :)
Please, explain what do you men under `iOS agent's source code`

**Comment by Sabomato** [comment]
In [Zebrunner MCloud repository](https://github.com/zebrunner/mcloud) this is what is said in the first paragraph:

> Zebrunner MCloud is a Device Farm for automated test execution (Appium) and **remote web access by humans** to physical devices (Android and **iOS**) including phones, tablets, and TVs. 

I haven't been able to try out the farm with iOS devices, but is all the manual interaction on the device handled by [go-ios](https://github.com/danielpaulus/go-ios) or are you using anything else?
