### ISSUE TITLE
after doing down/stop per udid we have to block device for automatic startup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#122]
down by udid doesn't disable launch services and as result in 10-15s we again kick off services startup.
it has sense to find a way and block this device temporary until explicit `./zebrunner.sh start udid` is executed
also global `./zebrunner.sh start` call should unblock all stopped/downed devices

**Comment by vdelendik** [comment]
done. to test make sure to 
1. do stop and stop using different udid
-> stopped devices can't be started automatically by syncServices (review agents.log to confirm)

2. do start using udid
-> device becomes unfrozen, services started

3. do regular `./zebrunner.sh start`
-> all devices should be unfrozen, services started one-by-one as wda doesn't support parallel start

**Comment by dhreben** [comment]
Verified.
