### ISSUE TITLE
Its not relevant message about frozen-udid file after ./zebrunner.sh down udid

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#123]
**Steps:**

1./zebrunner.sh down udid

`Logs: mkdir: ./tmp/frozen-b09f...........5: File exists`

**Actual result**: Its not a relevant message about frozen-udid file after ./zebrunner.sh down udid

**Comment by vdelendik** [comment]
fixed adding `mkdir -p ...` argument for folder creation

**Comment by dhreben** [comment]
Verified.
