### ISSUE TITLE
upgrade to 2.1 don't pull latest changes for stf

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#128]
as we clone single branch we can't switch into the new one and pull changes...
as result old sources are deployed from 2.0 release.
let's investigate what might be done to automate this process.

**Comment by vdelendik** [comment]
fixed by cloning stf with all branches and checkouting to the released version (2.4 as of today).
during the verification we have to inspect that upgrade steps have `rm -rf stf` step. As result for new upgrades we can easily pull latest changes from released branch

**Comment by dhreben** [comment]
Verified.

Steps:

1. rm -rf stf
2. ./zebrunner sh setup
3. Confirm rebuild STF components
