### ISSUE TITLE
The device still works after deleting it from device.txt

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#13]
**Test scanario:**

1.Register  iphone or tablet in devices.txt
2.Start Appium/WDA and STF services.
3.Remove device from device.txt 
4.tail -f ./logs/agents.log

**Actual result**: The device still works after deleting it from device.txt

<img width="1100" alt="Screenshot 2020-12-14 at 19 13 46" src="https://user-images.githubusercontent.com/50950954/102106317-76b06480-3e41-11eb-845a-44486ae881e6.png">

**Comment by vdelendik** [comment]
closing as working as designed. if you remove it from whitelisted devices.txt you have to control devices state in advance and stop services on your own
