### ISSUE TITLE
Update Xcode to 14.0

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#139]
To support the new version of iOS 16,0 we need to update Xcode to  14.0 version

**Comment by dhreben** [comment]
**Done.**

Xcode is updated to 14.0 version
For testing need :

1. Update Xcode from Appstore
2. Open Xcode and check if all is well with the certificate.
3. Open Xcode >Build Settings
4. Check that checkbox has "Yes" on Validate Workspace
5. Open cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport on mac and download to linux new DeveloperDiskImages 16.0

**Comment by dhreben** [comment]
Verified.
Done

**Comment by namilkimfree** [comment]
Xcode 14.0 
appium-webdriveragent build ->  Cannot link directly with dylib/framework, your binary is not an allowed client of /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework/XCTAutomationSupport for architecture arm64

**Comment by marcelozenjob** [comment]
> check Xcode 14 issue
> 
> The interaction between the Xcode14 and appium 1.x version is the problem. If you downgrade Xcode to 13.x version it will work, or install and set up appium 2 beta. See this for more infromation: [appium/appium#17497](https://github.com/appium/appium/issues/17497)
> 
> i have issue

In another issue, I have posted a quick fix for it using Xcode 14 and Appium 1.22.3.
https://github.com/appium/appium/issues/17497#issuecomment-1317180418
