### ISSUE TITLE
reuse go-ios proxy for redirecting wda requests 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#143]
related tickets:
https://github.com/zebrunner/appium/issues/148
https://github.com/zebrunner/mcloud-device/issues/118
https://github.com/zebrunner/mcloud-agent/issues/155

**Comment by vdelendik** [comment]
done. testing should include setup simulators and physical iOS devices on mac and running appropriate automation scripts.

**Comment by dhreben** [comment]
Verified.
