### ISSUE TITLE
ip detection for modern 4.10.12 wda is broken

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#144]
we know that for 4.1.4 we could parse wda host/ip from log message during wda startup.
but in the modern wda releases log message format was changed:
{"fields.msg":"2022-12-13 16:56:20.796411+0300 WebDriverAgentRunner-Runner[27575:4609350] ServerURLHere-\u003ehttp://192.168.89.19:8100\u003c-ServerURLHere\n","fields.time":28890969122592,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":27575,"time":"2022-12-13T05:56:20-08:00"}

as result we can't detect ip address anymore and can't register iOS device in STF.
let's adjust parser steps to support both, old and new wda versions.

https://github.com/zebrunner/appium/issues/147

**Comment by vdelendik** [comment]
fixed by removing this code completely. after using port forwarding for WDA we don't need anymore it's ip address.

**Comment by dhreben** [comment]
Closed
