### ISSUE TITLE
automate wda build/install for iOS device during setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#154]
1. update readme moving part about wda ipa building
2. ask about path to ipa during setup (use go-ios to prepare devices: auto mount, wda uninstall and install, use xcrun simctl to make similar for simulators)

**Comment by vdelendik** [comment]
done for physical devices. During setup we are going to do:
1. dev images auto mount
2. stop and uninstall any existing wda
3. install using new path to ipa provided during setup
4. start new wda on device
5. test it's successful status and wanr in case of any problem
6. stop test launch

For simulators added such warning:
$DEVICE_NAME ($DEVICE_UDID): WebDriverAgent on simulator should be installed in advance via XCode!

For currently disconnected physical devices added such warning:
$DEVICE_NAME ($DEVICE_UDID): WebDriverAgent on simulator should be installed in advance via XCode!

For the case when new WebDriverAgent.ipa can't be started such warning is displayed:
$DEVICE_NAME ($DEVICE_UDID): WebDriverAgent is not started! Analyze ${DEVICE_LOG} for details.

**Comment by dhreben** [comment]
Verified
