### ISSUE TITLE
improve confirm for WebDriverAgent.ipa path after ./zebrunner.sh setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#164]
It would be great to add a health check if WebdriverAgent.ipa is present on mcloud-ios after confirm WebdriverAgent.ipa path.
If WebdriverAgent is not present on Mcloud-ios, user can see echo

Eсho "WebdriverAgent is not present on Mcloud-ios, please add"

**Comment by vdelendik** [comment]
done. in case of any inaccessibility of the ipa we produce such warning and ask again about valid path:
```
WARNING! Unable to find WebDriverAgent.ipa using provided path: <invalid-path>
```

**Comment by dhreben** [comment]
Verified.
