### ISSUE TITLE
add unique temp dir for startAppium using "--tmp" cli

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#17]
```
  --tmp "${BASEDIR}/tmp/AppiumData/${udid}" \
```

**Comment by vdelendik** [comment]
fixed in develop: https://github.com/zebrunner/mcloud-ios/commit/30824a2dfb3d8d580305ebe5e85f9ab80bc86753

during a testing make sure you see generated folders like './tmp/AppiumData/<udid>' after appium stratup

**Comment by dhreben** [comment]
Verified.
