### ISSUE TITLE
stop operation should kill processes even for disconnected devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#175]
let's don't verify actual device state during `./zebrunner.sh stop` and do processes kill explicitly by uuid.
to test we have to
1. ensure no listening service is up&running, still TBD how to organize it should be like `launchctl unload ~/Liabrary/LaunchAgents/syncZebrunner.sh`
2. disconnect physical device
-> processes still up&running
3. launch .`./zebrunner.sh stop`
-> no more stf/appium and ios forward to wda processes up&running for this device udid.

**Comment by vdelendik** [comment]
done

**Comment by dhreben** [comment]
Verified.

```
/Users/idmcloud/tools/mcloud-ios/metaData/b09..................243f862b5.json
{"err":"Device 'b09fa2............7243f862b5' not found. Is it attached to the machine?","level":"fatal","msg":"error getting devicelist","time":"2023-01-12T19:46:34+03:00"}
ios ruwda pid: 9293
```
