### ISSUE TITLE
WDA should be killed by syncWDA after extra verification

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#18]
pay attention that simulators related code works fine as well

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/mcloud-ios/commit/2f7dd85da8cc541472eb147d9958e29c9faf0fa3
As a test scenario disconnect physical device.
-> in ~10 seconds syncWDA should be started
-> in the next 5 seconds we should double check that device really disconnected
-> WDA should be stopped, message added to `./logs/agents.log`

**Comment by dhreben** [comment]
Verified
