### ISSUE TITLE
revert: do explicit stop on setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#188]
it was discovered that if we do setup without stop we have a conflict on first start (because regular start and recovery do it at the same time).

let's ask during setup about permission to sop everything and continue with stopped state

**Comment by vdelendik** [comment]
done. we say that unable to proceed with setup until services are stopped. also at the end we suggest to start.
if on 1st question we response `n` - we just exit from setup with warning.

**Comment by dhreben** [comment]
Verified.

**Comment by vdelendik** [comment]
reopening to review again and maybe disable stop on setup...

**Comment by vdelendik** [comment]
reverted stop operation during setup. after #218 resolving we can skip useless and boring wda restart. as result it should minimize risks of the conflicts between setup and recovery.
also changed final comment after setup to:
```
Your services needs to be restarted using './zebrunner.sh restart'!
```
