### ISSUE TITLE
Error: rm *.ip: No such file or directory

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#19]
rm: /Users/.../mcloud-ios/metaData/*.ip: No such file or directory

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/mcloud-ios/commit/b5e148deb2d7191dd61049343eb305a97132e174

test scenario: after disconnecting physical device 
->WDA should be stopped
-> `./metaData/<udid>.txt` file removed
-> no errors in agents.log anymore

**Comment by dhreben** [comment]
**Test scenario:**

1../killAllWDA.sh
2.Open /mcloud-ios/metaData

**Actual result:**  Udid.txt  files are presented on metadata folder

<img width="1114" alt="Screenshot 2020-12-21 at 19 53 47" src="https://user-images.githubusercontent.com/50950954/102801841-d4efc100-43c6-11eb-9f5b-830c16348709.png">

**Comment by vdelendik** [comment]
1. updated metadata file names for wda ip scripts, they are named using `ip_<udid>.txt` convention
2. updated stf and appium sync script to detect wda state based on presence of this file per device udid. No file means no process and stop script execution.
3. added explicit `ip_<udid>.txt` removal from metadata folder on killing all wda services

**Comment by dhreben** [comment]
**Test scenario:**

1. ./zebrunner..sh down
2. Check that all processes were killed
3. Open /mcloud-ios/metaData/

**Actual result**: `ip_<udid>.txt` files are presented on metadata folder

<img width="909" alt="Screenshot 2020-12-22 at 16 36 36" src="https://user-images.githubusercontent.com/50950954/102894451-2dc96300-4474-11eb-92ad-076b99b82eb4.png">

**Comment by vdelendik** [comment]
nice catch! fixed inside unified zebrunner.sh as well

**Comment by dhreben** [comment]
Fixed:

<img width="749" alt="Screenshot 2020-12-22 at 18 43 24" src="https://user-images.githubusercontent.com/50950954/102906371-95d47500-4485-11eb-86c8-24c2b4684e79.png">
