### ISSUE TITLE
devicemanager plist is not loaded after setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#192]
it seems like if any WDA is not verified correctly we don't proceed with the rest of setup steps

**Comment by vdelendik** [comment]
fixed indirectly. devicemanage launch agent scipt is loaded on start now.

**Comment by dhreben** [comment]
**Verified.**
Steps:

1. ./zebrunner.sh start
2. launchctl list | grep zebrunner

**Expected result:** Devicemanager plist is loaded after start
