### ISSUE TITLE
troubleshooting: verify launchctl rules status

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#195]
during setup if rules not loaded we can't organize valid recovery and devices manager services. So `launchctl list | grep com.zebrunner.mcloud.UDID` is an important part of the setup and should be verified in advance. In case of any problem with it -> stop process and warn user.

**Comment by vdelendik** [comment]
added extra verification onto the start0device where we have launch agent recovery script load.
during the testing it would be great to emulate negative case to see such error:
```
LaunchAgent recovery script is not loaded for $DEVICE_NAME udid: $DEVICE_UDID!
```

if no ideas howto do it with configuration I can recommend to make explicit mistake in `zebrunner.sh` for example:
```
launchctl list | grep com.zebrunner.mcloud.$udid > /dev/null 2>&1
->
launchctl list | grep com.zebrunner.mcloud.$udidINVALID > /dev/null 2>&1
```

with this explicit mistake we shouldn't start services (appium, wda and stf) for all devices and print the error

**Comment by dhreben** [comment]
Verified.

Steps:

1. ./zebrunner.sh stop --> Stopping MCloud services...
2. ./zebrunner.sh start udid --> WARNING! LaunchAgent recovery script is not loaded for iPhone_13_mini udid: 0000.........8801E!
