### ISSUE TITLE
Error: line 287: down: command not found  after  ./zebrunner.sh shutdown 

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#199]
**Steps:**

1../zebrunner.sh shutdown

**Actual result:**  Error: line 287: down: command not found  after  ./zebrunner.sh shutdown 

```
./zebrunner.sh: line 287: down: command not found
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
Removing devices metadata and STF
```

**Comment by vdelendik** [comment]
fixed error message about `down`. for unloading launchctl error, please double check. it might be shown only if you run shutdown twice as I understand.

**Comment by dhreben** [comment]
**Steps:**

1. ./zebrunner.sh shutdown  

**Actual result**: Down has worked correctly, but the message has appeared since the 1st run ./zebrunner.sh shutdown

```

MCloud services stopped.
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
Removing devices metadata and STF
```

**Comment by vdelendik** [comment]
@dhreben, nice catch. 
fixed removing unload on shutdown completely. we already have this option on stop
