### ISSUE TITLE
iOS: provide easy way to sync simulators as we do for physical device

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#2]
syncDevices.sh use `ios-deploy` to detect connected physical devices and put their metadata into connectedDevices.txt.
The similar operation for simulators are too heavy and we can't do it every 5-10 seconds but we can create syncSimulators.sh which should be executed at once during setup and generate simulators metadata.
Among commands we can use:
```
instruments -s devices 
xcrun simctl list
xcrun xctrace list devices
```

3rd one is the best option as it shows only loaded simulators.

Benefits: 
1) we can do syncup of simulators on-demand when needed (new setup or new simulator configured)
2) we can remove all independent logic for simulators and use phone/tablet/appletv as a type
3) whitelisted simulators should be declared in devices.txt
4) all available will be generated on-demand and registered in connectedSimulators.txt

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/mcloud-ios/commit/520ad2a58800b8282c836587c25961f4ae91d85b

as a testing register phone and tablet in devices.txt, syncup simulators and run Mobile-iOS-Demo-Test on both "devices".

**Comment by dhreben** [comment]
Test scenario:

**1 case:**

1. Open Xcode and add Iphone and tablet devices
2. Run  `xcrun simctl list`  and check that iphone and tablet are appears
3. Run `xcrun simctl boot` with Udid iphone and ipad
4. Register iphone and tablet in devices.txt
- Add version
- Add Udid
- Add Apium,WDA,Mjpeg,IWDP,STF_screean ,STF_appium ports.

4. Run `launchctl load ~/Library/LaunchAgents/syncWDA.plist  `
5. Run  `launchctl load ~/Library/LaunchAgents/syncSTF.plist `
6. Run  `launchctl load ~/Library/LaunchAgents/syncAppium.plist `
7. Run  `launchctl load ~/Library/LaunchAgents/syncDevices.plist`
8. `./startAppium.sh` with Udid Iphone
9. `./startAppium.sh` with Udid tablet
10. `./startWDA.sh` with Udid Iphone
11. `./startWDA.sh` with Udid tablet
12. `./startSTF.sh` with Udid Iphone
13. `./startSTF.sh` with Udid tablet

14. Open Jenkins
15. Run RegisterOrganization
16. Run RegisterRepository
17. Tap RegisterHubCredentials
18. Tap build with Parameters
 - enter your folder name
 - provider is mcloud
 - http://demo:demo@stage.solvd.com/mcloud/wd/hub

19. Open Mobile-iOS-Demo-Test
20. Tap build with Parameters
21. Delete "ANY" on capabilities and enter deviceName= Iphone name
22. Tap build
23. Run another time Mobile-iOS-Demo-Test with deviceName= Ipad name
24. Tap build

**Expected result:** Carina-demo is loaded.

<img width="750" alt="Screenshot 2020-12-14 at 18 22 52" src="https://user-images.githubusercontent.com/50950954/102099504-65fbf080-3e39-11eb-9ca5-5c07d1a372fb.png">

**`Case 2:`**

1.Register  iphone and tablet in devices.txt
2.Start Appium/WDA and STF services.
3.Remove device from device.txt 
4.tail -f ./logs/agents.log

**Actual result**:The device still works after deleting it from device.txt

<img width="1100" alt="Screenshot 2020-12-14 at 19 13 46" src="https://user-images.githubusercontent.com/50950954/102105483-87aca600-3e40-11eb-93e3-7cf6179c332a.png">

Closed. Opened new ticket https://github.com/zebrunner/mcloud-ios/issues/13
