### ISSUE TITLE
automate stf cli location detection

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#20]
```
#TODO: parametrize hardcoded path to stf cli
nohup node /Users/build/tools/stf/lib/cli ios-device --serial ${udid} \
```

need finish with above TODO comment and remove extra step(s) in README

**Comment by vdelendik** [comment]
fixed. during the testing try to clone mcloud-ios into diffenret folders under usr home and let's say even `/tmp`

**Comment by dhreben** [comment]
Verified.
