### ISSUE TITLE
killAll* scripts shoud be renamed somehow

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#21]
killAllWDA.sh, killAllSTF.sh and killAllAppium.sh: all these files were named long time ago. We have to rename all of them and think about consolidated start/stop/down/restart etc operations

**Comment by vdelendik** [comment]
14 shell scripts is too much for the iOS slave... need something consolidated

**Comment by vdelendik** [comment]
start/stop/kill scripts combined into the single zebrunner.sh
@dhreben, try to test without any documentation and let me know if new approach is better or not...

**Comment by dhreben** [comment]
Verified.Closed new issues
 https://github.com/zebrunner/mcloud-ios/issues/25
https://github.com/zebrunner/mcloud-ios/issues/26
