### ISSUE TITLE
infinite start loop

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#211]
**Steps:**

1. run ./zebrunnner.sh setup 

**Actual result:** The command line does not appear after finishing the ./zebrunner.sh setup/start

```
      WARNING! WDA is not started for iPhone_14 udid: 0A55.......................3B6C85!
      WARNING! WDA is not started for Apple_Watch_8 udid: CF....................0795B7!

```
after clicking **Enter** button the command line appear

```
      WARNING! WDA is not started for iPhone_14 udid: 0A55.......................3B6C85!
      WARNING! WDA is not started for Apple_Watch_8 udid: CF....................0795B7!

id...ds-Mac-mini:mcloud-ios idm....ud$ 
```

**Comment by vdelendik** [comment]
fixed removing completely question about `Start now`.
just added warning that services should be started right after setup using `zebrunner.sh start`

**Comment by dhreben** [comment]
Still repro after  run ./zebrunner.sh start

**Comment by vdelendik** [comment]
@dhreben - let's make a call when you have time. still unclear for me your definition of "command line appeared"

**Comment by dhreben** [comment]
Repro after run ./zebrunner.sh restart

**Comment by vdelendik** [comment]
reverted changes from #208 to fix particular problem.

**Comment by dhreben** [comment]
Still repro after run ./zebrunner.sh start/restart 


      WARNING! WDA is not started for Apple_Watch_8 udid: CFBD4CE0-4496-4EB8-9746-DE19EF358AFB!
iPhone_12 (00............001E) is disconnected!
iPhone_8_Plus (d6afc6............b6ebb11) is disconnected!
iPhone_11 (000.........802E) is disconnected!
Waiting while services are up&running...

**Comment by vdelendik** [comment]
refactored startup procedure completely. it should exit asap showing in the console such info:
```
./zebrunner.sh start
Verify startup status using './zebrunner.sh status'
```

**Comment by dhreben** [comment]
Fixed
