### ISSUE TITLE
still have invalid schema for tvOS

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#216]
xctestconfig should be updated for tvOS devices.
```
       echo "[$(date +'%d/%m/%Y %H:%M:%S')] Starting WebDriverAgent application on port $WDA_PORT"
-      ios runwda --bundleid=$ZBR_WDA_BUNDLE_ID --testrunnerbundleid=$ZBR_WDA_BUNDLE_ID --xctestconfig=WebDriverAgentRunner.xctest \
+      ios runwda --bundleid=$ZBR_WDA_BUNDLE_ID --testrunnerbundleid=$ZBR_WDA_BUNDLE_ID --xctestconfig=WebDriverAgentRunner_tvOS.xctest \
```

**Comment by vdelendik** [comment]
it has sense to bump up to go-ios v1.0.102 where `test-runner-bundle-id` and `xctest-config` can be omitted.
https://github.com/danielpaulus/go-ios/releases/tag/v1.0.102

**Comment by vdelendik** [comment]
removed these args to use default one which were used during ipa building... also registred new ticket to upgrade to v1.0.102+ go-ios on mac

**Comment by vdelendik** [comment]
@dhreben, make sure to test howto define these settings during ipa building:
 test-runner-bundle-id and xctest-config

**Comment by vdelendik** [comment]
fixed. based on `tvOS` in DEVICETYPE we override schema to `WebDriverAgentRunner_tvOS` for wda startup

**Comment by dhreben** [comment]
Fixed.
