### ISSUE TITLE
provide an option to skip WDA reinstall

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#218]
during an upgrade there is no sense to reinstall WDA when nothing changed from appium webdriver agent point of view. So in 90% cases uninstall and install of wda is useless.

so let's ask 1st of all if user want to install/reinstall and continue only if accepted

**Comment by vdelendik** [comment]
done, extra logic implemented to ask about webdriveragent.ipa reinstall:
```
Uninstall and install WebDriverAgent application?
  Note: required only first time or if ipa was updated.
Continue? y/n [n]:
```

So if you install it already first time or install manually - you can just skip this step.
@dhreben, also make sure to test that reply is remembered and during next setup it should auto populate y or n based previous action.

**Comment by dhreben** [comment]
Verified.
