### ISSUE TITLE
bump up to the latest go-ios

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#222]
bump up to the latest go-ios
https://github.com/zebrunner/stf/issues/758

**Comment by vdelendik** [comment]
it is required for #216 so make sure to adjust upgrade steps!

**Comment by vdelendik** [comment]
readme updated. the same should be added into the upgrade steps

**Comment by dhreben** [comment]
Reopened with https://github.com/zebrunner/mcloud-ios/issues/216

**Comment by vdelendik** [comment]
moved to 2.5 as removing some runwda args fail...

**Comment by vdelendik** [comment]
updated readme: https://github.com/zebrunner/mcloud-ios/commit/aa2a27c69290c74840bacc47b193e769feaeccab#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30

**Comment by dhreben** [comment]
Verified.
