### ISSUE TITLE
remember `Rebuild STF sources?` choice

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#223]
let's remeber user input for rebuilding stf sources. Also let's print full SmartTestFarm name

**Comment by vdelendik** [comment]
done, including text update:
```
Rebuild SmartTestFarm sources?
Rebuild? y/n [y]:n
```

@dhreben - make sure to test both scenarios and confirm that choice is remembered and used during the next setup.

**Comment by dhreben** [comment]
Verified
