### ISSUE TITLE
terminal commands are broken after `./zebrunner.sh start`

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#227]
right after the `./zebrunner.sh` we can't use terminal commands. i.e. we type something but nothing is displayed... as only enter is pressed we see the output but original command is not displayed. issue seems related to #211

**Comment by vdelendik** [comment]
fixed. @dhreben, make sure to test that:
1. `./zebrunner.sh start` works fine and doesn't corrupt terminal. 
2. `./zebrunner.sh start udid` works fine and doesn't corrupt terminal. 
3. recovery works fine when we kill any stf service per device
4. reconnect works fine for device

**Comment by dhreben** [comment]
Verified.

**Comment by vdelendik** [comment]
reopening as some changes still expected so we have to retest in upcoming 2.4.6

**Comment by vdelendik** [comment]
we have to retest using develop branch as startup again was updated: https://github.com/zebrunner/mcloud-ios/pull/233/files

potentially it might break terminal again(
