### ISSUE TITLE
fix detection of `is starting` status

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#229]
after fixing #227 we broke "is starting" device state

**Comment by vdelendik** [comment]
fixed reusing status-device function: https://github.com/zebrunner/mcloud-ios/pull/233/files

**Comment by dhreben** [comment]
Fixed

Steps:

**Case 1:**

1. ./zebrunner.sh stop udid
2. ./zebrunner.sh status

`iPhone_7_Plus (de0d7...........39755c17941) is stopped.`

**Case 2:** 

1. /zebrunner.sh start [udid]
2. ./zebrunnner.sh  status
 - after 5 sec

` iPhone_7_Plus (de0...................39755c17941) is starting.`

- when device available on STF 

`iPhone_7_Plus (de0...................755c17941) is healthy.`

**Case 3:** 

1. reconnect device 
2. ./zebrunner sh status

`iPhone_7_Plus (de0d7a3........5c17941) is disconnected!`

**Case 4:**

1. Connect device
2. ./zebrunner.sh status


`iPhone_7_Plus (de0...................755c17941) is healthy.`
