### ISSUE TITLE
 .env doesn't exist after git clone on develop branch

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#23]
Test scenario:

1.git clone --branch develop https://github.com/zebrunner/mcloud-ios.git
2. nano zebrunner.sh 

Actual result:   .env doesn't exist after git clone on develop branch

<img width="1034" alt="Screenshot 2020-12-29 at 19 41 53" src="https://user-images.githubusercontent.com/50950954/103299624-ff1c3100-4a0d-11eb-963c-0e04afc038b5.png">

```
#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd ${BASEDIR}

source ${BASEDIR}/.env

if [[ -f backup/settings.env ]]; then
  source backup/settings.env

**Comment by vdelendik** [comment]
fixed

**Comment by dhreben** [comment]
Fixed
