### ISSUE TITLE
rename com.qaprosoft.carina.grid to com.zebrunner.mcloud.grid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#28]
due to the updated package names we have to adjust [configgen.sh](https://github.com/zebrunner/mcloud-ios/blob/910cd33cfed4106979a07770fcb3214bfef8822f/configs/configgen.sh#L35) as well

**Comment by vdelendik** [comment]
done. during testing setup ios slave.
-> appium should appear in selenium hub console like http://hostname/mcloud/grid/console

**Comment by dhreben** [comment]
Verified.
