### ISSUE TITLE
Add only ios-infra one click solution

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/mcloud-ios#3]
Let's think about adding one click solution for only macOS infra. So, you'll be able to get only necessary and available for macOS containers and scripts.

**Comment by vdelendik** [comment]
it might be organized as unified `./zebrunner.sh setup` script.
it should 
0. Ask about required argument like STF public ip, selenium hub etc
1. List already connected devices
2. Provide possibility to authorize all of them answering A or one-by-one
3. List/Filter existing available simulators (need an index around each simulator)
4. Provide possibility to authorize simulator by entering index and pressing enter
5. Generate devices.txt according to the latest requirements
6. clone stf and install/link via node v8.17.0 9think about prerequisites check before start)
7. Ask about automatic stratup and load updated launch agent scripts 

./zebrunner.sh down should unload agent scripts and kill processes
./zebrunner.sh stop - just stop existing processes (wda, appium and stf)

**Comment by vdelendik** [comment]
done. setup procedure automated and described in readme: https://github.com/zebrunner/mcloud-ios/blob/master/README.md

**Comment by dhreben** [comment]
Verified.
