### ISSUE TITLE
Error : No such file or directory backup/settings.env.original after ./zebrunner.sh setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#30]
**Test scenario:**

1.Git clone --single-branch --branch master https://github.com/zebrunner/mcloud-ios.git
2.cd mcloud-ios
3.Update device.txt.
4../zebrunner.sh setup

**Actual result:** ./zebrunner.sh error line 62: backup/settings.env.original: No such file or directory.

<img width="1011" alt="Screenshot 2021-01-19 at 21 20 26" src="https://user-images.githubusercontent.com/50950954/105076476-28276300-5a9c-11eb-94c4-9a499aa0b561.png">

**Comment by vdelendik** [comment]
fixed

**Comment by dhreben** [comment]
fixed
