### ISSUE TITLE
Error : Echo_warning command not found after ./zebrunner.sh setup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#38]
**Test scenario:**

1.Git clone on my ec2 instance : `git clone --recurse-submodule --branch develop https://github.com/zebrunner/mcloud-ios.git`
2.`./zebrunner.sh setup`

**Actual result** : ./zebrunner.sh: line 33: echo_warning: command not found

**Comment by vdelendik** [comment]
fixed

**Comment by dhreben** [comment]
Fixed.
