### ISSUE TITLE
Add lost dependencies to package.json file

### ISSUE THREAD

**Issue by kolyakrasnik** [zebrunner/mcloud-ios#4]
Currently we have to install some extra dependencies for iSTF. There are :
`npm install promise
  npm install request-promise
  npm install websocket-stream
  npm install mjpeg-consumer
  npm install udid`

Let's add these modules to package json to get avoid additional steps during iSTF installation.

**Comment by vdelendik** [comment]
we have to test on fresh mac if these steps still needed and if possible fully automate using `setup` procedure and npm install

**Comment by vdelendik** [comment]
fixed in readme adding the only requirement to install `brew install zeromq`
