### ISSUE TITLE
Landscape mode launch application(com.apple.springboard)  window sizes (width and height) are getting wrong values values

### ISSUE THREAD

**Issue by Veeru5c4** [zebrunner/mcloud-ios#42]
Hi
I have tested WDA code in landscape mode launch application(com.apple.springboard) width and height are getting wrong values
appium version : 1.19.0
xcode : 12.4
iOS : 14.4
Device: ipad 7th genaration

Launch icons touches window sizes are 
command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
o/p: {
    "value": {
        "width": 1080,
        "height": 1080
    },
    "sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

**why landscapde mode launch icons (com.apple.springboard) same width and height ?**

After open applications in landscape mode window sizes are correct

command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
o/p:
 {
    "value": {
        "width": 1080,
        "height": 810
    },
    "sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

In portrait mode launch icons and after app's getting correct values

command : http://192.168.0.5:8100/session/613286B9-3FBB-49FE-AE5C-B093F3E442E9/window/size
{
    "value": {
        "width": 810,
        "height": 1080
    },
    "sessionId": "613286B9-3FBB-49FE-AE5C-B093F3E442E9"
}

Can you please help this issue

**Comment by vdelendik** [comment]
closed as dupe to have a single ticket: https://github.com/zebrunner/stf/issues/177

**Comment by dhreben** [comment]
Сlosed
