### ISSUE TITLE
stop/down should kill starting processes as well

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#43]
as WDA can't be started in parallel we have some limitations and do extra verification of the existing startup process for wda and session...

So issue occur when someone run stop or down operation which kill allready started processes and keep "starting..."
As result next start will wait until corrupted "starting" finish by timeout.

We have to review stop/down kill logic and kill any start-wda, strat-session zebrunner procecces forcibly

**Comment by vdelendik** [comment]
fixed adding `plikk -f zebrunner.sh` at the end of stop method.
it should guarantee that you killed started and starting operations.

to test follow:
1. setup and start services
2. do `ps -ef | grep zebrunner` to see when services start processes. 
3. during slow start-wda operation run `./zebrunner.sh down`
-> make sure that existing `./zebrunner.sh start-wda ...` was killed

**Comment by dhreben** [comment]
Fixed.

![Screenshot 2022-01-21 at 16 50 48](https://user-images.githubusercontent.com/50950954/150538263-381022b1-31fc-444a-b5a5-aa3285f601c4.png)
