### ISSUE TITLE
Discrepancy between actual iOS device state and displayed screen in STF

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-ios#46]
This problem occurs when a lot of actions are accomplished on iOS device within short period of time and all frames couldn't be updated in a such swift time period -> user receives slight inconsistency between actual state of device (e.g. 6-th screen was reached after 30 seconds activity) and what could be observed on device (e.g. actions on 3-rd\4-th screen are reflected) in STF.

**Comment by vdelendik** [comment]
in mcloud 2.0 we plan to provide an option to connect iOS devices to Linux hardware which is more stable and more powerful from server hardware perspective... This particular ticket moved onto the 2.1 as we still don't know if this mcloud-ios agent should be developed in future. The only potential reason is simulators which might be started and integrated only on Mac OS based on software and legal aspects

**Comment by vdelendik** [comment]
@rkatuzhanets, how about speed for devices connected via Linux?

**Comment by vdelendik** [comment]
let's test in upcoming v2.4 . Several improvements organized to make it faster

**Comment by dhreben** [comment]
Verified with stag and prod project , but still repro on another prod project and I think the issue is related to the network
