### ISSUE TITLE
Include opencv installation step to iOS-slave setup process

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-ios#53]
So as to reduce the amount of additional actions which are required for automation process (e.g. working with images) it would be better to have opencv library installed just during the setup process.

**Comment by vdelendik** [comment]
@rkatuzhanets, closing as won't fix because we don't install appium during setup as well. to support image recognition admin should setup appium+opencv correctly on their own

**Comment by dhreben** [comment]
Verified. 

<img width="555" alt="Screenshot 2022-01-21 at 12 36 26" src="https://user-images.githubusercontent.com/50950954/150503355-e01ea133-41a3-4927-a1cc-cf8e79d85fb2.png">
