### ISSUE TITLE
Deliver healthcheck job for tracking wda\appium\stf statuses

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-ios#54]
The idea of this health check is to track current wda\appium\stf statuses and just in case of potential obstacles, e.g. when IP address of real device couldn't be obtained and appium\stf couldn't be started all active processes could be killed and setup procedure can be kicked off again automatically.

**Comment by vdelendik** [comment]
that's should be already part of the syncServices function which detect state of the devices/wda/appium/stf and start/stop when necessary. need to define exact problematic scenario and test

**Comment by dhreben** [comment]
*Test scenario:**

1.  ios-device:
`ps -ef |  grep ios-deviceps `
` kill -9 pid process`

**Expected result:** Devices  is available on  STF , WDA is restarted automatically15 sec


2. Appium:
`ps -ef |  grep appium`
`pkill -9 pid process`

**Expected result:**. Devices  is available on  STF , WDA is restarted automatically 15 sec.

3. WDA:

`ps -ef | grep xcodebuild`
` kill -9 pid process` 

**Expected result:**.  Device is available on STF , WDA is restarted automatically  after 15 sec.
