### ISSUE TITLE
iOS smartphones related info isn't altered once devices.txt file is updated

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-ios#57]
The problem is that once user has delivered several changes to **devices.txt,** restarted current infrastructure and opened STF to interact with real device old information for this device (e.g. **OS**) is still reflected under STF

**Comment by vdelendik** [comment]
let's review device.txt content and remove as much as possible from this place. Ideally we should keep only udid, type is under the question but looks required if we couldn't detect it on our own.
As about ports it might be useful to provide just range for all devices but still TBD as change is too serious and might affect all kind of advanced usage with proxy etc.
Version definitely must be removed and populated by stf service on start automatically

**Comment by vdelendik** [comment]
fixed in scope of https://github.com/zebrunner/stf/issues/284
we do os version, window size, battery info on every wda session startup and updating dta in rethinkdb...

it is not planned to be fixed in mcloud-ios implementation at all so no verification required
