### ISSUE TITLE
Appium and stf should depends on wda startup only

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#59]
In recent release appium and stf services startup depends on started wda session.
Sometimes it can’t happen and we don’t use device by automation.
It should be fixed as appium could start sessions on its own.
So when wda session is not started we could have troubles and slowness of manual usage only which not affect automation at all.

**Comment by vdelendik** [comment]
existing WDA session is optional as of now because for automation it is not required.
at the same time we should send into the appium/stf logs for each device warning message: `Integration with STF might be broken/slow as WDA session was not detected!`

To test it is recommended:
1. setup mcloud-ios as usual
2. remove manually all `metaData/session_*` files
3. stop/kill appium and stf
```
./zebrunner.sh stop-appium
./zebrunner.sh stop-stf
```
4. wait until launch service automatically start appium and stf
5. as we manually removed `session_*` files I expect we can emulate invalid WDA session
-> in every appium/stf log file per each device we should see such warning message:
`Integration with STF might be broken/slow as WDA session was not detected!`

**Comment by dhreben** [comment]
Fixed.
