### ISSUE TITLE
verify and create ~/Library/LaunchAgents folder during setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#60]
on fresh macOS ~/library/launchAgents folder might be missed.
as result setup process is broken.

**Comment by vdelendik** [comment]
fixed. to test we have to shutdown everything and remove
```
rm -rf ~/Library/LaunchAgents
```
do a setup
-> it should finish successfully w/o any errors. services might be started

**Comment by dhreben** [comment]
Fixed.
