### ISSUE TITLE
investigate possibility to use iOS devices from Linux platforms

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#63]
Mac is not a server hardware and has common personal OS problems when using as part of mobile device farm.
Let's investigate another solutions to be able to attach and use them from Linux OS.
https://github.com/shamanec/ios-appium-docker
https://libimobiledevice.org/

**Comment by vdelendik** [comment]
Done. My env has 3 iPhones connected via Linux: http://52.7.165.168/stf

do basic acceptance manually to verify the ticket

**Comment by dhreben** [comment]
Verified.
