### ISSUE TITLE
User isn't able to interact with iOS 15 devices

### ISSUE THREAD

**Issue by rkatuzhanets** [zebrunner/mcloud-ios#68]
WIth the current implementation IOS 15 devices are available under STF, yet it's impossible to interact with them, only grey screen is displayed.
<img width="427" alt="iOS15Screen" src="https://user-images.githubusercontent.com/21850997/139422967-7e3735d6-818b-43e0-9048-b0c3ae126706.png">

**Comment by vdelendik** [comment]
fixed as part of the new cross platform stf release: https://github.com/zebrunner/stf/milestone/15?closed=1
iPhone 7 on stage farm can be used successfully with 15.x version

**Comment by dhreben** [comment]
Fixed.
