### ISSUE TITLE
improve prerequisites verification before setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#69]
let's organize quick verification of the required components before starting actual setup with error'ing into the console in case of any problem, for example as of now we see error on 660 line only!
```
./zebrunner.sh: line 660: /usr/local/bin/ios-deploy: No such file or directory
```
Also let's update docs adding ios-deploy as obligatory prerequisite

**Comment by vdelendik** [comment]
done, before setup we do verification that such components obligatory installed and available in PATH:
ios-deploy, xcodebuild,git, ffmpeg and cmake.

Also "light" verification for appium and ios utility. Light means just echoing warning with ability to proceed with setup.

**Comment by dhreben** [comment]
Verified.
