### ISSUE TITLE
non-default websocket port can't be used

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#70]
After the setup using non-default port we still continue to use 80 or 443 default ports

**Comment by vdelendik** [comment]
fixed. as a test scenario we have to configure STF with iOS slave using non default 7777 port for example.
After setup iOS agent device should be connected and visible in STF as websocket should goto
ws://host:7777/d/udid/device-port

**Comment by dhreben** [comment]
Verified.
