### ISSUE TITLE
Cannot load real ios devices into Master host

### ISSUE THREAD

**Issue by antuking** [zebrunner/mcloud-ios#75]
Hello,

I'm trying setup ios slave for real device which the Master host address and Curren node (iOS slave) host address have the same mac machine or two specific mac machine. Here is the log which set up for ios slave:
https://gist.github.com/antuking/cacf452c55a903d1480511c98c53cadb

I got that the Master host should setup on Linux machine. But I don't have this stuff atm. Please help me resolve this.

P/s: I installed all of initialize steps already. This way occurs on one or two host machine.

![image](https://user-images.githubusercontent.com/19822174/149704282-f699292c-9d9e-4231-9538-6abe610dee27.png)

**Comment by vdelendik** [comment]
@antuking after setup slave it is recommended to start mcloud-ios services using `./zebrunner.sh start` and analyze `./logs/...` files.
I was able to connect iOS device into the both mcloud versions: 1.8 and upcoming 2.0.
closing as can't repro...
