### ISSUE TITLE
automate or add steps about adding go-ios utility into the PATH

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#76]
to control device state on low level we start using go-ios utility instead of ios-deploy. As result we have to download and put latest go ios utility into the `/usr/local/bin` for example and maybe document it in additions

**Comment by vdelendik** [comment]
added one more required step: https://github.com/zebrunner/mcloud-ios/tree/develop#readme
also light verification exists during setup with warn message: `go-ios utility is missed! Some operations might be broken!`

to test I can recommend to remove ios utility for example and temporary move xcodebuild into xcodebuild.bak to check that hard and light cheks work as expected

**Comment by dhreben** [comment]
Verified.
