### ISSUE TITLE
non-finished `setup` process corrupt .env file

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#77]
if we start `./zebrunner.sh` and interrupt process before providing valid input data we lose all our settings in .env.
zebrunner.sh should be fixed to load content from .env.original only after providing all input data from user!

**Comment by vdelendik** [comment]
fixed. to reproduce the problem I can recommend:
1. clone and setup cloud-ios from master branch
-> everything is configured, `.env` has valid settings
2. start again `./zebrunner.sh setup`, provide let;s say only protocol and interrupt process via Ctrl+C
-> review again `.env` file to see that you haven't valid values for stf master host, node hot, appium path
3. switch to the develop branch and repeat steps 1-2

**Comment by dhreben** [comment]
Verified.
