### ISSUE TITLE
improve stop/down operations

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-ios#81]
Let't improve stop/down operations:
1. `./zebrunner.sh stop` should unload services if enabled and stop/kill processes.
2. `./zebrunner.sh down` should unload services if enabled, stop/kill processes, delete logs and tmp
3. `./zebrunner.sh shutdown` should unload services if enabled, stop/kill processes, delete logs/tmp and metaData

**Comment by vdelendik** [comment]
done. improved stop/down and shutdown based on description

**Comment by dhreben** [comment]
Verified.
