### ISSUE TITLE
clone STF by release tag

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#83]
cloning and building stf should be done by tag instead of master. that should allow us to use master branch of stf much more easier

**Comment by vdelendik** [comment]
done. to test make a setup and verify by:
```
cd stf
git status
-> "Not currently on any branch." message is displayed
git log
-> "commit 8c3ed419e073e8f53754cf99e6aee90d4a37c9e7 (HEAD, tag: 2.0)" is displayed
```

**Comment by dhreben** [comment]
Verified.

![Screenshot 2022-01-25 at 17 17 29](https://user-images.githubusercontent.com/50950954/150993681-1a59a121-54d2-439d-98f6-5188066332b3.png)
