### ISSUE TITLE
integrate iOS simulators into the MCloud-STF

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#87]
We have to provide regular way to operate with iOS simulators via selenium/appium grid and STF.
Automated + Manual usage required.

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-ios/pull/118

during the testing make sure to verify that
1. in selenium grid simulators are registered with valid platformVersion number:
![image](https://user-images.githubusercontent.com/4551455/160887286-7e87d45c-d774-4286-95e5-f4a4437a9966.png)
2. simulators are available in STF for manual usage
3. Mobile-iOS-Simulator-Demo-Test carina-demo job might be executed on simulators (hopefully as for a long time we didn't test it:)
Note: use `udid=..` as capability to start on simulator

**Comment by dhreben** [comment]
Verifed.
