### ISSUE TITLE
no need to track wda `session_ip` anymore

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#91]
wda usage refactored a lot and we don't need it anymore up&running.
inspect our code which parse/use `session_ip` and clean it up where possible

**Comment by vdelendik** [comment]
done. testing should include basic acceptance and verification of iOS jobs
-> log and video artifacts should be published in reporting

**Comment by dhreben** [comment]
iOS-jobs running and successfully completed.
