### ISSUE TITLE
speedup appium and stf services startup at the beginning

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#92]
due to the limitations of xcodebuild we can't launch simultaneously several WDA processes and organized it in foreground call and runtime log parser.
At the same time appium and stf services for exact device might be started as only wda started, 1st session tested.
So let's invetsigate possibility to start appium/stf services for device as soon as wda is ready without huge delay. When we have 50 devices and 1-2 min for wda startup after the cleanup then we have ~50-100m pause when iOS devices are not accessible

**Comment by vdelendik** [comment]
done. during the testing we have to test such command for `./zebrunner.sh`
start 
stop
down
start udid
stop udid

Note: actions with udid should be done only from VNC session. Not tested at all by me...

**Comment by dhreben** [comment]
Down and start verified on prod
Stop verified on stage
Start udid  and stop udid verified on stage without VNC session
To verify the ticket and test the VNC, I am waiting for a fix with the video recording

**Comment by dhreben** [comment]
Verified.
