### ISSUE TITLE
setup process should ask about s3 compatible storage details

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#95]
as of now as workaround I put s3 related bucket/tenant vars into the backup/settings.env
```
declare -x BUCKET="..."
declare -x TENANT=".."
declare -x PLATFORM_NAME="ios"
```

it has sense to ask about these settings during setup and remember automatically

**Comment by vdelendik** [comment]
one more required env var
```
declare -x APPIUM_APPS_DIR="/opt/appium-storage"
```

**Comment by vdelendik** [comment]
done. during the setup we should ask about potential s3 storage integration and if yes ask about bucket and tenant.
as results these settings must be used by video recording scripts automatically

**Comment by dhreben** [comment]
Verified.

```
AWS S3 storage
Bucket [...............]: 
[Optional] Tenant [..........]: 
Bucket: .............
Tenant: ....
Continue? y/n [y]:
```
