### ISSUE TITLE
improve setup providing an option to skip stf building

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-ios#98]
When nothing is changed during git pull for stf there is no sense to rebuild stf sources again.
But to make option more controllable let's ask in terminal if user wanna to do force rebuild even if no changes during the pull to be able to modify something manually and rebuild

**Comment by vdelendik** [comment]
done. we do pull and display it's status. When state is `Already up to date.` user might skip rebuilding answering "n".
Example of the setup with rebuilding
```
Pull STF updates:
Already up to date.

Rebuild STF sources?
Confirm? y/n [y]:
Building iSTF component...
Now using node v8.17.0 (npm v6.14.8)
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
```

**Comment by dhreben** [comment]
Verified
